# Lights-Drone
DE: Ein KI-Projekt zur steuerung von Drohnen mit eingebautem Solar licht, Personenerkennung und deren Beleuchtung bei Nach auf einem spezifizierten Grundstück.
EN: An AI-Project for activating and controlling Drones with implemented Solar Light, detection of People and there lightening at Nicht at a specified Property.

## Ziel / goal
DE: Das Projekt soll KI-Modelle trainieren, um Personen zu erkennen wenn Sie ein Grundstück betreten und diese bei Dunkelheit mit einem eingebauten Solar-Licht beleuchten.
EN: This Project shold tain AI-Modells to detect People on one Property and in darkness enlighten dem with an implemented Solar-Light.

## Technologien / technologies
- Python  
- Azure AI  

## Funktionen / functions
DE: Erkennung von Menschen, Folgen der Persone mit einer Drone, einschalten des Lichtes, aufladen
EN: Detection of People, follow this person with a drone, activating the light, reload

## Zukunftspläne  / to dos
DE: Drohnenmodell heraussuchen, Kompatibelität mit Azure AI notwendig, Aufnahmemöglichkeit für ein Solar Licht wenn nicht bereits vorhanden, Programmierung von AI Vision, konfigurieren der Flugbahn.
EM: Search out a fittig drone modell, needs to be compatible to azure ai, need to have space for a solar light if not already implemented, programming AI Vision, configure a flight-path. 

